version: '3.8'

services:
  vibemap-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibemap-app
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/vibemap_db
    command: python -m visualize.plot_tsne_3d
